import {
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    IonButton,
    IonIcon,
    IonItem,
    IonInput,
    IonInputPasswordToggle,
    IonSpinner,
    IonLabel,
    IonText,
    IonList,
    IonCard,
    IonCardHeader,
    IonCardTitle,
    IonCardContent,
    IonTabBar,
    IonTabButton,
    IonFabButton,
    IonFab,
    IonTabs,
    IonButtons,
    
  } from '@ionic/angular/standalone';
  
  export const IonicCommonComponents = [
    IonButton,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonContent,
    IonHeader,
    IonIcon,
    IonInput,
    IonInputPasswordToggle,
    IonItem,
    IonLabel,
    IonList,
    IonSpinner,
    IonTabBar,
    IonTabButton,
    IonText,
    IonTitle,
    IonToolbar,
    IonFabButton,
    IonFab,
    IonTabs,
    IonButtons,
    
  ];
  